method: bayes
metric:
  goal: minimize
  name: val_loss_epoch
parameters:
  model.encoder_dropout:
    distribution: uniform
    max: 0.5
    min: 0.2
  model.encoder_model_learning_rate:
    distribution: uniform
    max: 1e-04
    min: 1e-07
  model.path_name:
    value: Sweepy
  model.udtube_dropout:
    distribution: uniform
    max: 0.5
    min: 0.1
  model.udtube_learning_rate:
    distribution: uniform
    max: 0.001
    min: 1e-05
  seed_everything:
    value: 42
