seed_everything: 1995
trainer:
  max_epochs: 100
  max_time: 00:12:00:00
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 10
        verbose: true
  logger:
    - class_path: lightning.pytorch.loggers.CSVLogger
      init_args:
        save_dir: /Users/Shinji/UD_Russian-SynTagRus/models
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: syntagrus
        save_dir: /Users/Shinji/UD_Russian-SynTagRus/models
data:
  model_dir: /Users/Shinji/UD_Russian-SynTagRus/models
  train: /Users/Shinji/UD_Russian-SynTagRus/ru_syntagrus-ud-train.conllu
  val: /Users/Shinji/UD_Russian-SynTagRus/ru_syntagrus-ud-dev.conllu
