#!/bin/bash

set -eou pipefail

cd ../..

en() {
    local -r MODEL_DIR="$(mktemp --directory)"
    udtube fit \
        --config=tests/testdata/udtube_config.yaml \
        --data.model_dir="${MODEL_DIR}" \
        --data.train=tests/testdata/en_train.conllu \
        --data.val=tests/testdata/en_train.conllu \
        --model.encoder=google-bert/bert-base-cased \
        --model.use_xpos=True
    udtube predict \
        --ckpt_path="${MODEL_DIR}/lightning_logs/version_0/checkpoints/last.ckpt" \
        --config=tests/testdata/udtube_config.yaml \
        --data.model_dir="${MODEL_DIR}" \
        --data.predict=tests/testdata/en_train.conllu \
        --model.encoder=google-bert/bert-base-cased \
        --model.use_xpos=True \
        > tests/testdata/en_expected.conllu 
    udtube test \
        --ckpt_path="${MODEL_DIR}/lightning_logs/version_0/checkpoints/last.ckpt" \
        --config=tests/testdata/udtube_config.yaml \
        --data.model_dir="${MODEL_DIR}" \
        --data.test=tests/testdata/en_train.conllu \
        --model.encoder=google-bert/bert-base-cased \
        --model.use_xpos=True \
        > tests/testdata/en_expected.test
    rm -rf "${MODEL_DIR}"
}

ru() {
    local -r MODEL_DIR="$(mktemp --directory)"
    udtube fit \
        --config=tests/testdata/udtube_config.yaml \
        --data.model_dir="${MODEL_DIR}" \
        --data.train=tests/testdata/ru_train.conllu \
        --data.val=tests/testdata/ru_train.conllu \
        --model.encoder=DeepPavlov/rubert-base-cased \
        --model.use_xpos=False
    udtube predict \
        --ckpt_path="${MODEL_DIR}/lightning_logs/version_0/checkpoints/last.ckpt" \
        --config=tests/testdata/udtube_config.yaml \
        --data.model_dir="${MODEL_DIR}" \
        --data.predict=tests/testdata/ru_train.conllu \
        --model.encoder=DeepPavlov/rubert-base-cased \
        --model.use_xpos=False \
        > tests/testdata/ru_expected.conllu 
    udtube test \
        --ckpt_path="${MODEL_DIR}/lightning_logs/version_0/checkpoints/last.ckpt" \
        --config=tests/testdata/udtube_config.yaml \
        --data.model_dir="${MODEL_DIR}" \
        --data.test=tests/testdata/ru_train.conllu \
        --model.encoder=DeepPavlov/rubert-base-cased \
        --model.use_xpos=False \
        > tests/testdata/ru_expected.test 
    rm -rf "${MODEL_DIR}"
}

main() {
    en
    ru
}

main
