# lightning.pytorch==2.0.5
seed_everything: true
trainer:
  num_nodes: 1
  precision: 32-true
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 80
  max_steps: -1
  check_val_every_n_epoch: 1
  log_every_n_steps: 20
model:
  path_name: UDTube
  model_name: bert-base-multilingual-cased
  udtube_dropout: 0.5
  encoder_dropout: 0.2
  udtube_learning_rate: 0.001
  encoder_model_learning_rate: 2e-5
  pooling_layers: 4
data:
  train_dataset: el_gdt-ud-train.conllu
  val_dataset: el_gdt-ud-dev.conllu
  batch_size: 2
  convert_to_um: true
  reverse_edits: true