# lightning.pytorch==2.0.5
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 2
        monitor: loss_step
        mode: min
  fast_dev_run: false
  logger: WandbLogger
  max_epochs: 100
  min_epochs: 3
  max_steps: -1
  min_steps: null
  max_time: null
  check_val_every_n_epoch: 1
  log_every_n_steps: 16
model:
  path_name: UDTube
  model_name: bert-base-multilingual-cased
  learning_rate: 0.001
  pooling_layers: 4
data:
  train_dataset: <ADD_FILE_PATH>
  val_dataset: <ADD_FILE_PATH>
  batch_size: 16
  convert_to_um: true
  reverse_edits: true